### ISSUE TITLE
Cofiguration.yaml code doesnt work.

### ISSUE THREAD

**Issue by kelvincabaldo07** [TarheelGrad1998/files#12]
when i add the config yaml line. it says end of the stream or a document separator is expected. see screenshot [https://imgur.com/a/cQk51dS](url)
![Screenshot_20220120_184043](https://user-images.githubusercontent.com/30632175/150323567-2f088e2e-b527-45fe-9137-c6b424fe6eb0.png)

**Comment by TarheelGrad1998** [comment]
Hrm, that would seem to indicate an issue elsewhere in your config file.  

Do you have a sensor section elsewhere?  I think you can have only one, which you'd need to put the new platform section under that.

BTW, what is generating those errors?  Is that something in VS Code or similar?

**Comment by WesleyLiekens** [comment]
I get the same error.

i have these in configuration.yaml
sensor: !include sensors.yaml

and in sensors.yaml

- platform: files
    folder: /config/www/images
    filter: '**/*.jpg'
    name: gallery_images
    sort: date
    recursive: True

**Comment by Dobbiiey** [comment]
could you test following style?
```
files:
  - sensor:
      - name: gallery_images
        folder: /config/www/images
        filter: "**/*.jpg"
        sort: date
        recursive: True

```
